name: ucua_staging
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_auth: ^4.19.4
  fluttertoast: ^8.2.5
  flutter_spinkit: ^5.2.1
  firebase_core: any
  cloud_firestore: ^4.17.2
  image_picker: ^1.1.1
  carousel_slider: ^4.2.1
  firebase_storage: ^11.7.5
  intl: ^0.19.0
  firebase_messaging: ^14.9.4
  badges: ^3.1.2
  flutter_launcher_icons: ^0.13.1
  cached_network_image: ^3.3.1
  font_awesome_flutter: ^10.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/ucua-logo.png
    - assets/ucua-logo2.png
    - assets/pfp.png
    - assets/manage.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/ucua-logo.png"
